/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
/**
 *
 * @author Aeon
 */
import API.IContact;
import API.IWindowManager;
import control.ContactCheck;
import control.dao.ContactDAOFactory;
import control.dao.DataToDB;
import ini.DBtype;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class EditContactUI extends javax.swing.JFrame implements IWindowManager {
    
    private String Fname;
    private String Lname;
    private String Email;
    private String Tel;
    private String Mtel;
    private String Address;
    private String City;
    private IContact editContact;

    /**
     * constructor with parameters
     * @param editContact 
     */
    public EditContactUI(IContact editContact) {
        
        initComponents();
        
        this.editContact = editContact;
        //getContactToEdit();
        setDataToFields();
    }

    /**
     * 
     */
    private void getContactToEdit() {
        
        this.Fname=editContact.getFirstname();
        this.Lname=editContact.getLastname();
        this.Email=editContact.getEmail();
        this.Tel=editContact.getTelephone();
        this.Mtel=editContact.getMtelephone();
        this.Address=editContact.getAddress();
        this.City=editContact.getCity();
      
        //metafora pliroforiwn epafis sti forma pros epeksergasia
        setDataToFields();
    }
    
    /**
     * thetw sta pedia tis plirofories tis epafis
     */
    private void setDataToFields() {
        
        jTextFieldFname.setText( editContact.getFirstname() );
        jTextFieldLname.setText( editContact.getLastname() );
        jTextFieldEmail.setText( editContact.getEmail() );
        jTextFieldTel.setText( editContact.getTelephone() );
        jTextFieldMtel.setText( editContact.getMtelephone() );
        jTextFieldAddress.setText( editContact.getAddress() );
        jTextFieldCity.setText( editContact.getCity() );
    }
    
    private void getDataFromFields() {
        
        editContact.setFirstname( jTextFieldFname.getText() );
        editContact.setLastname( jTextFieldLname.getText() );
        editContact.setEmail( jTextFieldEmail.getText() );
        editContact.setTelephone( jTextFieldTel.getText() );
        editContact.setMtelephone( jTextFieldMtel.getText() );
        editContact.setAddress( jTextFieldAddress.getText() );
        editContact.setCity( jTextFieldCity.getText() );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonReset = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldLname = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jLabelMtel = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jLabelLname = new javax.swing.JLabel();
        jTextFieldMtel = new javax.swing.JTextField();
        jLabelFname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AddressBook - New Contact");
        setMinimumSize(new java.awt.Dimension(400, 395));
        setPreferredSize(new java.awt.Dimension(400, 395));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonClose.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
            .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonReset)
                .addGap(62, 62, 62)
                .addComponent(jButtonUpdate)
                .addGap(18, 18, 18)
                .addComponent(jButtonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldCity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldLname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEmail.setText("Email");

        jTextFieldFname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldFname.setToolTipText("");

        jTextFieldTel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelTel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTel.setText("Telephone");

        jLabelMtel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelMtel.setText("Mobile Tel.");

        jLabelCity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCity.setText("City");

        jTextFieldAddress.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelAddress.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelAddress.setText("Address");

        jLabelLname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelLname.setText("Lastname");

        jTextFieldMtel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelFname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelFname.setText("Firstname");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMtel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jTextFieldTel)
                    .addComponent(jTextFieldMtel)
                    .addComponent(jTextFieldFname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldLname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddress)
                    .addComponent(jTextFieldCity))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMtel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMtel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /**
      * kalw tin sunartisi apodwsis timwn
      * gia epanafora stis default plirofories tis epafis
      * @param evt
      */
    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        setDataToFields();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
    
        control.WindowManager windowManager=new control.WindowManager();
        windowManager.openFrame(new AddressBookUI());
        windowManager.closeFrame(this);
        
    }//GEN-LAST:event_jButtonCloseActionPerformed

    /**
     * otan o xristis pataei update, katharizw to contact p periexei ton user p theloume na ginei update kratontas to ID tou 
     * stin topiki idToUpdate. meta vazw ta kainouria stoixeia kai ta stelnw stin vash gia update me to ID p kratisa
     * @param evt 
     */
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        
        getDataFromFields();
        ContactCheck contactCheck=new ContactCheck(editContact);
        if(contactCheck.isProperContact())
        {
            try 
            {
                DataToDB dbData = new DataToDB( ContactDAOFactory.getInstance(DBtype.db_type) );
                dbData.updateContact(editContact);
                JOptionPane.showMessageDialog(null,"Contact updated!");
                
                control.WindowManager windowManager=new control.WindowManager();
                windowManager.openFrame(new AddressBookUI());
                windowManager.closeFrame(this);
            }
            catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(null,"error! can't save to database!!");
                Logger.getLogger(EditContactUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Error!! No proper contact to update!");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFname;
    private javax.swing.JLabel jLabelLname;
    private javax.swing.JLabel jLabelMtel;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldMtel;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addCancelListener(ActionListener listener) {
        
    }

    @Override
    public void addObjectCancelListener(Object listener) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void addCommitListener(ActionListener listener) {
       
    }

    @Override
    public void addObjectCommitListener(Object listener) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public IWindowManager getOwnerManager() {
        return null;
    }

    @Override
    public JFrame getFrame() {
        return this;
    }

    @Override
    public void setModalRelativeTo(IWindowManager winManager) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void disposeWindow() {
        this.dispose();
    }
}