package obfuscations.enums;

public enum SupportedObfuscations {
    ACCESS_MODIFICATION_PUBLIC,
    FLATTEN_PACKAGE_HIERARCHY,
    FUNCTION_OVERLOADING,
    FUNCTION_OUTLINING,
    FUNCTION_INLINING,
    VARIABLE_NAME,
    WATERMARK,
    ENCRYPT_STRINGS
}
